# Generated by Django 5.2.12 on 2026-06-14 02:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_sku_prefix_product_description"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorylot",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="inventoryunit",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="inventorylot",
            name="unit_cost",
        ),
        migrations.AddField(
            model_name="inventorylot",
            name="lot_type",
            field=models.CharField(
                choices=[
                    ("manifested", "Manifested"),
                    ("unmanifested", "Unmanifested"),
                ],
                default="unmanifested",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventorylot",
            name="purchase_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="inventorylot",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorylot",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="inventorylot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_processing", "Pending Processing"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="pending_processing",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="inventorylot",
            name="supplier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="cost_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="source_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="inventory.inventorylot",
            ),
        ),
        migrations.AlterField(
            model_name="inventorylot",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_lots",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryunit",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
