# Generated by Django 5.2.12 on 2026-06-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_inventorylot_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryunit",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
