# Generated by Django 5.2.12 on 2026-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_add_size_color_to_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryunit",
            name="qty",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
