# Generated by Django 5.2.12 on 2026-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventoryunit_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryunit",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
