# Generated by Django 5.2.12 on 2026-06-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sku_prefix",
            field=models.CharField(
                blank=True,
                help_text="3-letter prefix for internal SKUs (top-level categories only, e.g. CLO, ELC)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
