# Generated by Django 5.2.12 on 2026-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_sku_prefix_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hsn_item_number",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
