# Generated by Django 5.2.12 on 2026-07-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_hsn_item_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
